### ISSUE TITLE
Nested item update is not working

### ISSUE THREAD

**Issue by gyupro** [blackary/st.database#2]
You cannot update nested dictionary as follow

some_db['20230524'] = {"email": "something@gmail.com"}
some_db['20230524']["email"] = 'test@gmail.com'
some_db.items()
{'20230524':"email":"something@gmail.com"}

**Comment by blackary** [comment]
That is true, and is a side-effect of the effect that
- `some_db['key'] = blah` uses `__setitem__` so it updates the database
- `some_db['key']['email'] = blah` first does `__getitem__` to get the entry at `key` from the database, and THEN updates the retrieved object, rather than updating the source object in the dictionary with `__setitem__`.

You can work around this by doing
```python
entry = some_db['20230524'] # Grabs the entry from db with `__getitem__`
entry["email"] = "test@gmail.com" # Manipulates that object
some_db['20230524'] = entry # Saves that back to db with `__setitem__`
```

I can't think of a great workaround to make this happen automatically, unfortunately.
